import { ICity } from './cities.http';

export const cities: ICity[] = [
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Albania',
    city: 'Tirana',
    temperatureCelsius: 6.7,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Austria',
    city: 'Vienna',
    temperatureCelsius: 0.3,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Belarus',
    city: 'Minsk',
    temperatureCelsius: -4.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Belgium',
    city: 'Brussels',
    temperatureCelsius: 3.3,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Bulgaria',
    city: 'Sofia',
    temperatureCelsius: -0.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Croatia',
    city: 'Zagreb',
    temperatureCelsius: 0.3,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Croatia',
    city: 'Split',
    temperatureCelsius: 8.0,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Cyprus',
    city: 'Nicosia',
    temperatureCelsius: 10.6,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Denmark',
    city: 'Copenhagen',
    temperatureCelsius: 1.4,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Estonia',
    city: 'Tallinn',
    temperatureCelsius: -2.9,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Finland',
    city: 'Helsinki',
    temperatureCelsius: -3.9,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Finland',
    city: 'Kuopio',
    temperatureCelsius: -9.2,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Finland',
    city: 'Oulu',
    temperatureCelsius: -9.6,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'France',
    city: 'Marseille',
    temperatureCelsius: 8.4,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'France',
    city: 'Paris',
    temperatureCelsius: 4.9,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Germany',
    city: 'Berlin',
    temperatureCelsius: 0.6,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Germany',
    city: 'Frankfurt',
    temperatureCelsius: 1.6,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Greece',
    city: 'Piraeus',
    temperatureCelsius: 11.1,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Hungary',
    city: 'Budapest',
    temperatureCelsius: 0.4,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Iceland',
    city: 'Reykjavík',
    temperatureCelsius: -0.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Ireland',
    city: 'Dublin',
    temperatureCelsius: 5.3,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Italy',
    city: 'Milan',
    temperatureCelsius: 2.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Italy',
    city: 'Palermo',
    temperatureCelsius: 12.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Italy',
    city: 'Rome',
    temperatureCelsius: 7.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Italy',
    city: 'Napoli',
    temperatureCelsius: 8.7,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Latvia',
    city: 'Riga',
    temperatureCelsius: -4.7,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Lithuania',
    city: 'Vilnius',
    temperatureCelsius: -6.1,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Malta',
    city: 'Valletta',
    temperatureCelsius: 12.8,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Moldova',
    city: 'Chișinău',
    temperatureCelsius: -1.9,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Monaco',
    city: 'Monaco',
    temperatureCelsius: 10.2,
  },

  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Montenegro',
    city: 'Podgorica',
    temperatureCelsius: 5.0,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Netherlands',
    city: 'Amsterdam',
    temperatureCelsius: 3.4,
  },
  {
    id: Math.ceil(Math.random() * 10000),

    country: 'Norway',
    city: 'Bergen',
    temperatureCelsius: 1.5,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Norway',
    city: 'Oslo',
    temperatureCelsius: 4.3,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Poland',
    city: 'Cracow',
    temperatureCelsius: 1.0,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Poland',
    city: 'Warsaw',
    temperatureCelsius: 1.8,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Poland',
    city: 'Wrocław',
    temperatureCelsius: 0.0,
  },
  {
    id: Math.ceil(Math.random() * 10000),
    country: 'Portugal',
    city: 'Lisbon',
    temperatureCelsius: 11.6,
  },
];
